/* Categories */
INSERT OR IGNORE INTO categories (id, name) VALUES (1, 'Accommodation');
INSERT OR IGNORE INTO categories (id, name) VALUES (2, 'Architecture & Buildings');
INSERT OR IGNORE INTO categories (id, name) VALUES (3, 'Art');
INSERT OR IGNORE INTO categories (id, name) VALUES (4, 'Beauty & Wellness');
INSERT OR IGNORE INTO categories (id, name) VALUES (5, 'Charity & Community');
INSERT OR IGNORE INTO categories (id, name) VALUES (6, 'City tours');
INSERT OR IGNORE INTO categories (id, name) VALUES (7, 'Dating');
INSERT OR IGNORE INTO categories (id, name) VALUES (8, 'Education');
INSERT OR IGNORE INTO categories (id, name) VALUES (9, 'Employment');
INSERT OR IGNORE INTO categories (id, name) VALUES (10, 'Entertainment');
INSERT OR IGNORE INTO categories (id, name) VALUES (11, 'Environment');
INSERT OR IGNORE INTO categories (id, name) VALUES (12, 'Events');
INSERT OR IGNORE INTO categories (id, name) VALUES (13, 'Financial');
INSERT OR IGNORE INTO categories (id, name) VALUES (14, 'Food & Drink');
INSERT OR IGNORE INTO categories (id, name) VALUES (15, 'Fun');
INSERT OR IGNORE INTO categories (id, name) VALUES (16, 'Games');
INSERT OR IGNORE INTO categories (id, name) VALUES (17, 'Government & Politics');
INSERT OR IGNORE INTO categories (id, name) VALUES (18, 'Health');
INSERT OR IGNORE INTO categories (id, name) VALUES (19, 'Local information');
INSERT OR IGNORE INTO categories (id, name) VALUES (20, 'Local search & Directory Services');
INSERT OR IGNORE INTO categories (id, name) VALUES (21, 'Nature & Parks');
INSERT OR IGNORE INTO categories (id, name) VALUES (22, 'Nightlife');
INSERT OR IGNORE INTO categories (id, name) VALUES (23, 'Photo & video');
INSERT OR IGNORE INTO categories (id, name) VALUES (24, 'Real Estate');
INSERT OR IGNORE INTO categories (id, name) VALUES (25, 'Religion');
INSERT OR IGNORE INTO categories (id, name) VALUES (26, 'Social');
INSERT OR IGNORE INTO categories (id, name) VALUES (27, 'Sports & Leisure');
INSERT OR IGNORE INTO categories (id, name) VALUES (28, 'Stores & Shopping');
INSERT OR IGNORE INTO categories (id, name) VALUES (29, 'Tourist information');
INSERT OR IGNORE INTO categories (id, name) VALUES (30, 'Trading (market place)');
INSERT OR IGNORE INTO categories (id, name) VALUES (31, 'Transportation');
INSERT OR IGNORE INTO categories (id, name) VALUES (32, 'Universities & Research');
INSERT OR IGNORE INTO categories (id, name) VALUES (33, 'Weather');
INSERT OR IGNORE INTO categories (id, name) VALUES (34, 'Wifi hotspots');